# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'FOAM' do
    pod 'SDWebImage', '~>3.7'
    pod 'MobileVLCKit'
    pod 'HapticHelper', '~> 1.0'
    pod 'youtube-ios-player-helper'
    pod 'AutoScrollLabel'
end
